### ISSUE TITLE
角色名内包含old导致文本不会被判断为新文本以进行翻译

### ISSUE THREAD

**Issue by epq1176** [abse4411/projz_renpy_translation#1]
角色名内包含old导致文本不会被判断为新文本以进行翻译

**Comment by epq1176** [comment]
更正一下，是角色名以-old结尾的话，就不会被判定成新文本
在text_type()里面给old前面也加个空格应该就能解决了

**Comment by epq1176** [comment]
还有，判断变量的函数只能判断[]内只存在英文的情况，[]有符号等就会被忽略
判断有没有翻译过最好不要用是否存在英文字母，因为有时候人名地名会不翻译，以及文本内会存在变量，导致这段文本被标记成未翻译。再拿去机翻的话就可能自动翻回英文。建议换成判断文本内是否存在汉字

**Comment by abse4411** [comment]
> 更正一下，是角色名以-old结尾的话，就不会被判定成新文本 在text_type()里面给old前面也加个空格应该就能解决了

 感谢反馈，这来源于text_type的问题，这确实有效。后面将启用正则表达式进行匹配。:-)

**Comment by abse4411** [comment]
> 还有，判断变量的函数只能判断[]内只存在英文的情况，[]有符号等就会被忽略 判断有没有翻译过最好不要用是否存在英文字母，因为有时候人名地名会不翻译，以及文本内会存在变量，导致这段文本被标记成未翻译。再拿去机翻的话就可能自动翻回英文。建议换成判断文本内是否存在汉字

感谢反馈，

- 针对[]有符号等就会被忽略这种情可能发生类似:[[text], renpy会将它不会将它解释为变量，而输出为[text]，相当于“[[”为转义字符。这里判断变量名根据是一般编程语言中的定义，以字母或者下划线开头，且以数字、字母或者下划线构成字符串，这里还添加针对句点“.”的成员访问符号。

- 当时对于未翻译文本主要从源语言为英语出发，这种情况比较复杂，后面会进一步改进

**Comment by epq1176** [comment]
有可能做一个判断机翻文本是否重复的函数吗？有些时候脚本会把上一段对话的翻译当成下一段对话的翻译
当然如果没空的话我可以自己动手

**Comment by abse4411** [comment]
> 有可能做一个判断机翻文本是否重复的函数吗？有些时候脚本会把上一段对话的翻译当成下一段对话的翻译 当然如果没空的话我可以自己动手

这种情况出现于翻译过程中，某一次翻译结果输出框内容没有被清理，使得在新进入未翻译文本时候，代码误判断翻译完成导致此次翻译结果为上次翻译结果。一个解决方法是延长清空等待时间，不过这会增加翻译时间：
`
        try:
            # browser.find_element_by_class_name('text-delete').click()  #试图通过叉键清空
            self.inputArea.click()
            self.inputArea.send_keys(Keys.CONTROL, 'a')
            self.inputArea.send_keys(Keys.BACKSPACE)
        except:
            self.inputArea.clear()  # 否则直接清空输入框
        time.sleep(2)  # 等待清空延迟
`
你的解决方法也是可以，后面会增加一个判断检测输出框是否完全清除再进行下一轮的翻译。
