### ISSUE TITLE
彩云小译似乎更新了页面前端导致脚本无法定位到文本框

### ISSUE THREAD

**Issue by epq1176** [abse4411/projz_renpy_translation#10]
如题

**Comment by abse4411** [comment]
感谢反馈，在修期间您可以使用其他方式，如[savehtml](https://github.com/abse4411/projz_renpy_translation/tree/devp#%E4%BD%BF%E7%94%A8savehtml%E5%92%8Cloadhtml%E5%BF%AB%E9%80%9F%E7%BF%BB%E8%AF%91%E6%B5%8F%E8%A7%88%E5%99%A8%E8%87%AA%E5%B8%A6%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91)
