### ISSUE TITLE
彩云小译似乎更新了页面前端导致脚本无法定位到文本框

### ISSUE THREAD

**Issue by epq1176** [abse4411/projz_renpy_translation#11]
> Error in starting the web translator, 4212 untranslated line(s) will be not translated: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div[2]/div[1]/div[2]/div/div[1]/div[3]"}

**Comment by abse4411** [comment]
需要注意的是，exe还未更新，建议先用Python脚本运行。
