### ISSUE TITLE
AI翻译功能反馈

### ISSUE THREAD

**Issue by AIHardCore** [abse4411/projz_renpy_translation#12]
大佬，我尝试使用了AI翻译功能，但我观察到我的显存占用并没有上来了反而是cpu占用达到了70%，内存占用到达了18G。这是GPU没有介入工作吗？我安装教程安装了全部的依赖，并且我是可以正常使用SD的，不知道是哪里出了问题。我应该怎么检查我是否正确配置了环境？感谢大佬！！！
配置：
GPU：3060 12G 
CPU：AMD 5950X

**Comment by abse4411** [comment]
你好，你可以在项目的Python环境下尝试运行下面的脚本：
```python
import torch
print(torch.cuda.is_available())

a = torch.randn((1000,1000)).to('cuda')
for i in range(10000):
    a = a * a
```
在运行前可以先打开任务管理器查看显卡的性能面板，如果运行该脚本后输出为True，且显卡有段时间利用率不为0，说明你的环境已经正确装好了。鉴于你可以跑 SD模型，那应该是从本地加载模型到内存需要一定的时间，是否在开始翻译过程中没有显存占用？

**Comment by abse4411** [comment]
> > 你好，你可以在项目的Python环境下尝试运行下面的脚本：
> > ```python
> > import torch
> > print(torch.cuda.is_available())
> > 
> > a = torch.randn((1000,1000)).to('cuda')
> > for i in range(10000):
> >     a = a * a
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在运行前可以先打开任务管理器查看显卡的性能面板，如果运行该脚本后输出为True，且显卡有段时间利用率不为0，说明你的环境已经正确装好了。鉴于你可以跑 SD模型，那应该是从本地加载模型到内存需要一定的时间，是否在开始翻译过程中没有显存占用？
> 
> 你好，我运行你给的代码，报了个异常：AssertionError: Torch not compiled with CUDA enabled

应该是pytorch和cuda版本不对应，可以把环境中pytorch重新卸载在安装对应显卡版本的pytorch：https://github.com/abse4411/projz_renpy_translation#3%E5%AE%89%E8%A3%85cuda%E6%94%AF%E6%8C%81%E7%9A%84pytorch

**Comment by AIHardCore** [comment]
> > > 你好，你可以在项目的Python环境下尝试运行下面的脚本：
> > > ```python
> > > import torch
> > > print(torch.cuda.is_available())
> > > 
> > > a = torch.randn((1000,1000)).to('cuda')
> > > for i in range(10000):
> > >     a = a * a
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 在运行前可以先打开任务管理器查看显卡的性能面板，如果运行该脚本后输出为True，且显卡有段时间利用率不为0，说明你的环境已经正确装好了。鉴于你可以跑 SD模型，那应该是从本地加载模型到内存需要一定的时间，是否在开始翻译过程中没有显存占用？
> > 
> > 
> > 你好，我运行你给的代码，报了个异常：AssertionError: Torch not compiled with CUDA enabled
> 
> 应该是pytorch和cuda版本不对应，可以把环境中pytorch重新卸载在安装对应显卡版本的pytorch：https://github.com/abse4411/projz_renpy_translation#3%E5%AE%89%E8%A3%85cuda%E6%94%AF%E6%8C%81%E7%9A%84pytorch

我的CUDA版本是12.2，pytorch好像没有对应版本。所以可以安装了12.1版本的：pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121。不知道是不是这个问题

**Comment by abse4411** [comment]
> > > > 你好，你可以在项目的Python环境下尝试运行下面的脚本：
> > > > ```python
> > > > import torch
> > > > print(torch.cuda.is_available())
> > > > 
> > > > a = torch.randn((1000,1000)).to('cuda')
> > > > for i in range(10000):
> > > >     a = a * a
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 在运行前可以先打开任务管理器查看显卡的性能面板，如果运行该脚本后输出为True，且显卡有段时间利用率不为0，说明你的环境已经正确装好了。鉴于你可以跑 SD模型，那应该是从本地加载模型到内存需要一定的时间，是否在开始翻译过程中没有显存占用？
> > > 
> > > 
> > > 你好，我运行你给的代码，报了个异常：AssertionError: Torch not compiled with CUDA enabled
> > 
> > 
> > 应该是pytorch和cuda版本不对应，可以把环境中pytorch重新卸载在安装对应显卡版本的pytorch：https://github.com/abse4411/projz_renpy_translation#3%E5%AE%89%E8%A3%85cuda%E6%94%AF%E6%8C%81%E7%9A%84pytorch
> 
> 我的CUDA版本是12.2，pytorch好像没有对应版本。所以可以安装了12.1版本的：pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url [https://download.pytorch.org/whl/cu121。不知道是不是这个问题](https://download.pytorch.org/whl/cu121%E3%80%82%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%B8%8D%E6%98%AF%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98)

建议使用你当时可以跑SD环境来安装pytorch。
