### ISSUE TITLE
能否将自定义翻译做成类似于XUnity.AutoTranslator那样

### ISSUE THREAD

**Issue by HK1170961** [abse4411/projz_renpy_translation#17]
仅需要在配置文件中填入API 和密钥

**Comment by abse4411** [comment]
自定义翻译的意思可以自己写代某种翻译的实现代码集成到我们的工具中。

我想你的意思是使用翻译功能时候默认使用某一种翻译配置，这样使用翻译功能就不需要手动指定语言代码或者翻译服务提供商(从`t 1 -l schinese -t ts -n google`变为`t 1  -l schinese -t ts`)，简化后的命令可以送配置文件自动读取使用翻译服务提供商和翻译目标。这目前还没有这种功能，但是可以实现。一般来说这个可以用于在AI翻译和[UlionTse/translators](https://github.com/abse4411/projz_renpy_translation/issues/17#%E4%BD%BF%E7%94%A8uliontse-translators%E7%BF%BB%E8%AF%91)翻译。这将在后面版本提供


目前用的翻译源都是免费的，需要API密钥的翻译功能还没有。

**Comment by abse4411** [comment]
> 仅需要在配置文件中填入API 和密钥

[新增功能8](https://github.com/abse4411/projz_renpy_translation/blob/devp/README_zh.md#%E6%96%B0%E5%A2%9E%E5%8A%9F%E8%83%BD)可以关注以下， [AI翻译](https://github.com/abse4411/projz_renpy_translation/blob/devp/README_zh.md#%E4%BD%BF%E7%94%A8AI%E7%BF%BB%E8%AF%91)和[UlionTse/translators](https://github.com/abse4411/projz_renpy_translation/blob/devp/README_zh.md#%E4%BD%BF%E7%94%A8uliontse-translators%E7%BF%BB%E8%AF%91)翻译，命令后面添加`-a`参数就可以从配置文件自动加载翻译设置。例如：`t {index_or_name} -t ai -l {lang} -a` 和 `t {index_or_name} -t ts -l {lang} -a`

**Comment by abse4411** [comment]
> 仅需要在配置文件中填入API 和密钥

我之前理解错了，你说应该是像XUnity.AutoTranslator注入式翻译插件。目前正在开发中这种不用生成rpy文件的翻译功能，原型是做好了，但是后面需要开发GUI界面，由于时间有限，估计得等个一两周才能好。
