### ISSUE TITLE
打开提示问题

### ISSUE THREAD

**Issue by Yukarlna** [abse4411/projz_renpy_translation#18]
![QQ图片20240328165052](https://github.com/abse4411/projz_renpy_translation/assets/104445392/0b27bf89-b9c7-425e-95cd-551a4d348958)
![QQ图片20240328165107](https://github.com/abse4411/projz_renpy_translation/assets/104445392/cec095b7-13c9-4a46-9545-65667d4cfc00)

**Comment by abse4411** [comment]
应该是代理问题，关闭代理试试
