### ISSUE TITLE
即时翻译server_ui打开之后提示错误，translator无法运行

### ISSUE THREAD

**Issue by axiba1220** [abse4411/projz_renpy_translation#20]
![image](https://github.com/abse4411/projz_renpy_translation/assets/62327939/aad66607-125a-456d-aa49-e98eec245749)
计算机只懂一点点，不知道是不是系统变量配置问题，检查这个module是有的。还有我装了anaconda不知道有没有影响

**Comment by axiba1220** [comment]
运行main.exe提示没有torch。之前用过4.2版本来google翻译，没有问题，不记得有没有这个提示了。

**Comment by abse4411** [comment]
> 运行main.exe提示没有torch。之前用过4.2版本来google翻译，没有问题，不记得有没有这个提示了。

你可以把libs.7z重新下载解压，新版本后增加新的功能，需要用到新的库。

**Comment by abse4411** [comment]
> 运行main.exe提示没有torch。之前用过4.2版本来google翻译，没有问题，不记得有没有这个提示了。

main.exe没有AI翻译，所以提示没有torch是正常的

**Comment by axiba1220** [comment]
> > 运行main.exe提示没有torch。之前用过4.2版本来google翻译，没有问题，不记得有没有这个提示了。
> 
> 你可以把libs.7z重新下载解压，新版本后增加新的功能，需要用到新的库。

好的，感谢。你做这个工具虽然小白要学习一下，但真的好用
