### ISSUE TITLE
新版本0.4.5导入tl文件的几个问题

### ISSUE THREAD

**Issue by julienslink** [abse4411/projz_renpy_translation#22]
去年9月的时候用过大佬的项目，最近回来发现换了新版本，尝试的过程中发现几个问题，不知道是不是我的操作有错误
我的操作过程如图：
![1](https://github.com/abse4411/projz_renpy_translation/assets/46835195/8564021b-c8a1-4dfe-8720-8dd2504007c9)
发现大部分文本都被标为已经翻译过的，使用unmark全部转为未翻译，用se导出为excel后，发现导出的只有直接放在GamesofDepravityTheMotel-1.0-pc\game\tl\schinese文件夹下的rpy文件内容，而在GamesofDepravityTheMotel-1.0-pc\game\tl\schinese\events内的rpy文件未被提取出来。文件结构如下图
![2](https://github.com/abse4411/projz_renpy_translation/assets/46835195/dcd3317d-b262-44fb-a1f8-898114e11d4e)
不知道是我的哪一步操作有问题

**Comment by abse4411** [comment]
由于某些原因，对于已存在的rpy文件的对话翻译导入后，无法使用unmark将其转化为未翻译状态。如果需要修改这些对话，使用de和ue两个命令可以进行对话的导出和导入，如：
导出所有文本到excel（如果要仅导出已翻译的，后面附加`-s translated`，或者是未翻译的：`-s untranslated`）：
de 1 -l schinese 
在excel修改完后：
ue 1 -l schinese

**Comment by julienslink** [comment]
哦抱歉，我之前的描述没完全，我翻译的是一个新游戏，不是版本更新，使用的ty内的文件来自renpysdk的新生成。
对于这些新生成的rpy文件，在import那一步，
在ty/schinese/(某文件夹)内的rpy文件似乎没有被扫描到，无论是用se还是de导出的excel内都没有上述文件夹内的rpy文件内的数据

**Comment by julienslink** [comment]
> 哦抱歉，我之前的描述没完全，我翻译的是一个新游戏，不是版本更新，使用的ty内的文件来自renpysdk的新生成。 对于这些新生成的rpy文件，string类大部分标记为已翻译，Dialogue类全部被标记为已翻译 这种现象正常吗

新版本和之前的不一样了吗，不需要提前renpysdk生成ty文件了，直接用prozj对新游戏生成翻译文件？
另：能不能麻烦大佬抽时间把help表格里的内容写详细一点，比如格式和某些可选项的意思直接放在表格里，只有输错格式才能看见提示有点蛋疼

**Comment by abse4411** [comment]
> 哦抱歉，我之前的描述没完全，我翻译的是一个新游戏，不是版本更新，使用的ty内的文件来自renpysdk的新生成。 对于这些新生成的rpy文件，string类大部分标记为已翻译，Dialogue类全部被标记为已翻译 这种现象正常吗

是的，在new命令前如果已经存在rpy文件，那么这些在rpy的翻译都会被认为是已经翻译过的。如果要识别别成未翻译的，需要把对应语言目录下的rpy文件都删除了

**Comment by abse4411** [comment]
> > 哦抱歉，我之前的描述没完全，我翻译的是一个新游戏，不是版本更新，使用的ty内的文件来自renpysdk的新生成。 对于这些新生成的rpy文件，string类大部分标记为已翻译，Dialogue类全部被标记为已翻译 这种现象正常吗
> 
> 新版本和之前的不一样了吗，不需要提前renpysdk生成ty文件了，直接用prozj对新游戏生成翻译文件？ 另：能不能麻烦大佬抽时间把help表格里的内容写详细一点，比如格式和某些可选项的意思直接放在表格里，只有输错格式才能看见提示有点蛋疼

新版本全程不需要renpy sdk帮助，就可以读取翻译和生成翻译文件。  每个命令的用法，在输入一个命令后添加`-h`选项就可以显示完整的命令帮助。
