### ISSUE TITLE
是不是某些游戏不能导出对话

### ISSUE THREAD

**Issue by axiba1220** [abse4411/projz_renpy_translation#23]
![image](https://github.com/abse4411/projz_renpy_translation/assets/62327939/f75980c8-cfd2-4c71-b3d9-6c6220267f09)
不知道是不是部分游戏的结构不够标准化还是什么，提取不出对话。

我对renpy游戏的结构不是很了解，提取对话失败的两个游戏似乎脚本都在game目录下的rpa文件里，能提取对话的那个游戏则全都是rpy文件。

尝试把提取失败的游戏rpa文件解包了，删除TranslationIndex后重新import好像还是没生效，不知道是哪里做得不对。之前试过github上另一个叫Renpy Translator的项目 ，也经常遇到这个问题，对话无法提取。那个工具我还没翻译成功过。不过他有个术语表的功能还挺眼馋的，不知道我们这个项目怎么实现，尝试过导出到excel后替换名词，导回去之后就变成已翻译内容了，能不能用ue更新回默认语言？请教大佬

当然大部分游戏使用即时翻译都没有问题，但是必须先过一遍游戏再退回来稍微有点剧透，才想着用之前的提取全部对话来翻译。
(遇到过一次游戏使用即时翻译注入后，启动游戏能进去，一点开始游戏就报错的，因为是测试随便下的游戏就没在意）

**Comment by abse4411** [comment]
解包使用unren这个工具，在release中下载没有powershell字样的zip，把解压后的bat放在游戏根目录，启动，按回车，输入2，按回车，选择y，按回车 等待运行结束后，重新使用import导入即可

**Comment by abse4411** [comment]
要把翻译结果(已翻译的文本)某些单词替换成其他字词，用de命令，同时添加-s translated参数，导出已翻译文本为excel，在excel上全局替换后，保存，然后用ue命令更新就行

**Comment by abse4411** [comment]
即时翻译器，遇到错误的信息截图和游戏信息可以提供一下以便更好地改进程序，感谢

**Comment by axiba1220** [comment]
> 解包使用unren这个工具，在release中下载没有powershell字样的zip，把解压后的bat放在游戏根目录，启动，按回车，输入2，按回车，选择y，按回车 等待运行结束后，重新使用import导入即可

对你怎么知道我用的别的，用的rpaExtract。unren的git页面好像没有release可用了，在f95找到sam发的UnRen-1.0.11d.bat不知道有没有潜在问题？我把1-6都跑了一遍
![image](https://github.com/abse4411/projz_renpy_translation/assets/62327939/a2dd5d75-1f3b-4c2b-9cee-647171a3ab26)
然后果然有对话了！感谢老哥！
![image](https://github.com/abse4411/projz_renpy_translation/assets/62327939/b2b66dcf-6c61-4028-95eb-2970af94f808)

**Comment by axiba1220** [comment]
> 要把翻译结果(已翻译的文本)某些单词替换成其他字词，用de命令，同时添加-s translated参数，导出已翻译文本为excel，在excel上全局替换后，保存，然后用ue命令更新就行

额，我是想把原文的名词直接替换掉，然后让机器翻译，毕竟替换的都是名词对翻译影响应该不大(以前用百度翻译的时候感觉这个方法可行）。如果翻译之后再统一替换，就很难说机器把同一个名字翻译成几种译文了，倒不是不能找，就是比较麻烦。

似乎也可以直接修改rpy里的原文，改天试试。

**Comment by axiba1220** [comment]
> 即时翻译器，遇到错误的信息截图和游戏信息可以提供一下以便更好地改进程序，感谢

![image](https://github.com/abse4411/projz_renpy_translation/assets/62327939/70bbef89-e1ec-42ce-934d-072ba25e86f1)
启动的时候是这样

点开始后的错误信息
![image](https://github.com/abse4411/projz_renpy_translation/assets/62327939/26bdd005-1409-454c-b2e6-56e84084ff3e)
```
I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Not Implemented

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "script.rpyc", line 10, in script
  File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\ast.py", line 1918, in execute
    renpy.exports.say(None, "\n".join(narration), interact=False)
  File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\character.py", line 1337, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\translation\projz_translation.py", line 226, in projz_prefix_suffix
    code_str = node.get_code()
  File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\ast.py", line 722, in get_code
    raise Exception("Not Implemented")
Exception: Not Implemented

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
The Long Way 0.05.0
Tue Apr 30 00:46:03 2024
```

**Comment by abse4411** [comment]
> > 解包使用unren这个工具，在release中下载没有powershell字样的zip，把解压后的bat放在游戏根目录，启动，按回车，输入2，按回车，选择y，按回车 等待运行结束后，重新使用import导入即可
> 
> 对你怎么知道我用的别的，用的rpaExtract。unren的git页面好像没有release可用了，在f95找到sam发的UnRen-1.0.11d.bat不知道有没有潜在问题？我把1-6都跑了一遍 ![image](https://private-user-images.githubusercontent.com/62327939/326513956-a2dd5d75-1f3b-4c2b-9cee-647171a3ab26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTEwMTYsIm5iZiI6MTcxNDQxMDcxNiwicGF0aCI6Ii82MjMyNzkzOS8zMjY1MTM5NTYtYTJkZDVkNzUtMWYzYi00YzJiLTljZWUtNjQ3MTcxYTNhYjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE3MTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOTkyM2YyZWQ0ZTBiNjgwOTAyODU2YjM3ZmMxYWYzYzdhMTgwYzRiOWE1ZWZiZGNmZTU1MzZjMjJhMmZhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OxlFXBDrAMYkEseZyPgi9cMm06orND7bVjrUtgex1ao) 然后果然有对话了！感谢老哥！ ![image](https://private-user-images.githubusercontent.com/62327939/326515039-b2b66dcf-6c61-4028-95eb-2970af94f808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTEwMTYsIm5iZiI6MTcxNDQxMDcxNiwicGF0aCI6Ii82MjMyNzkzOS8zMjY1MTUwMzktYjJiNjZkY2YtNmM2MS00MDI4LTk1ZWItMjk3MGFmOTRmODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE3MTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlN2Q3ZGZhNTE1MTg3NDRjMDc2ZmE4MWZhMjc4ODlmODA2MTczMWVjYjMwYWM2ZjgwYTA5NzQ0ZmQ0Zjg3ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N8GZX5STEFEMcpdPob09I0nH0K1G4MQGqEiWPp03Vu0)

UnRen地址在readme这个章节有提供：https://github.com/abse4411/projz_renpy_translation?tab=readme-ov-file#3import-translations-of-a-language

**Comment by abse4411** [comment]
> > 即时翻译器，遇到错误的信息截图和游戏信息可以提供一下以便更好地改进程序，感谢
> 
> ![image](https://private-user-images.githubusercontent.com/62327939/326518592-70bbef89-e1ec-42ce-934d-072ba25e86f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTEwMTYsIm5iZiI6MTcxNDQxMDcxNiwicGF0aCI6Ii82MjMyNzkzOS8zMjY1MTg1OTItNzBiYmVmODktZTFlYy00MmNlLTkzNGQtMDcyYmEyNWU4NmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE3MTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NjM3NjE3N2YxODZiOTZhNWIxNmQyODVlMDgzOGM5ZDA5MTZjMzM5MjEwN2ZhYmM0M2ZjODUzZGM4ZTZlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qWmWix-3RMIs-1badQPJGtMQ3djgCMK2mApOJo1r_c) 启动的时候是这样
> 
> 点开始后的错误信息 ![image](https://private-user-images.githubusercontent.com/62327939/326519025-26bdd005-1409-454c-b2e6-56e84084ff3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTEwMTYsIm5iZiI6MTcxNDQxMDcxNiwicGF0aCI6Ii82MjMyNzkzOS8zMjY1MTkwMjUtMjZiZGQwMDUtMTQwOS00NTRjLWIyZTYtNTZlODQwODRmZjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE3MTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Y2E0NmQ1ZDU3NDk1YTBkNWY3NWVkYjUwYTczMWM5NjAwZTNlYzVlMmQwMzllN2ZiNWNmZGUzYmIxODk2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o1puPPgJjNuOGIYBC3hcCN0mxudbDs9aMktw8ZKrvgw)
> 
> ```
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> Exception: Not Implemented
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "script.rpyc", line 10, in script
>   File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\ast.py", line 1918, in execute
>     renpy.exports.say(None, "\n".join(narration), interact=False)
>   File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\exports.py", line 1474, in say
>     who(what, *args, **kwargs)
>   File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\character.py", line 1337, in __call__
>     what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
>   File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\translation\projz_translation.py", line 226, in projz_prefix_suffix
>     code_str = node.get_code()
>   File "P:\BaiduNetdiskDownload\7.waittrans\TheLongWay-0.05.0-pc\renpy\ast.py", line 722, in get_code
>     raise Exception("Not Implemented")
> Exception: Not Implemented
> 
> Windows-10-10.0.19041 AMD64
> Ren'Py 8.1.3.23091805
> The Long Way 0.05.0
> Tue Apr 30 00:46:03 2024
> ```

好的 感谢

**Comment by axiba1220** [comment]
> > > 解包使用unren这个工具，在release中下载没有powershell字样的zip，把解压后的bat放在游戏根目录，启动，按回车，输入2，按回车，选择y，按回车 等待运行结束后，重新使用import导入即可
> > 
> > 
> > 对你怎么知道我用的别的，用的rpaExtract。unren的git页面好像没有release可用了，在f95找到sam发的UnRen-1.0.11d.bat不知道有没有潜在问题？我把1-6都跑了一遍 ![image](https://private-user-images.githubusercontent.com/62327939/326513956-a2dd5d75-1f3b-4c2b-9cee-647171a3ab26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTEwMTYsIm5iZiI6MTcxNDQxMDcxNiwicGF0aCI6Ii82MjMyNzkzOS8zMjY1MTM5NTYtYTJkZDVkNzUtMWYzYi00YzJiLTljZWUtNjQ3MTcxYTNhYjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE3MTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOTkyM2YyZWQ0ZTBiNjgwOTAyODU2YjM3ZmMxYWYzYzdhMTgwYzRiOWE1ZWZiZGNmZTU1MzZjMjJhMmZhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OxlFXBDrAMYkEseZyPgi9cMm06orND7bVjrUtgex1ao) 然后果然有对话了！感谢老哥！ ![image](https://private-user-images.githubusercontent.com/62327939/326515039-b2b66dcf-6c61-4028-95eb-2970af94f808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTEwMTYsIm5iZiI6MTcxNDQxMDcxNiwicGF0aCI6Ii82MjMyNzkzOS8zMjY1MTUwMzktYjJiNjZkY2YtNmM2MS00MDI4LTk1ZWItMjk3MGFmOTRmODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE3MTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlN2Q3ZGZhNTE1MTg3NDRjMDc2ZmE4MWZhMjc4ODlmODA2MTczMWVjYjMwYWM2ZjgwYTA5NzQ0ZmQ0Zjg3ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N8GZX5STEFEMcpdPob09I0nH0K1G4MQGqEiWPp03Vu0)
> 
> UnRen地址在readme这个章节有提供：https://github.com/abse4411/projz_renpy_translation?tab=readme-ov-file#3import-translations-of-a-language

好的感谢老哥！之前没注意到这个。
五一快乐
