### ISSUE TITLE
初步試用跟心得

### ISSUE THREAD

**Issue by BlackZoneJweak** [abse4411/projz_renpy_translation#3]
我有两台电脑一台西文一台中文用新版的翻译程式，觉得旧版的准确率比较高，新版的速度比较快，可是有时候会翻译不到，或是没有加上@@ 或是 @$,還有一次出現三行出現相同翻譯（新版），不管原文是什麼，所以确定不是电脑的问题，因为一台刚好翻译西文，一台中文做有交叉比对，小弟我小小的心得目前还在努力研究中辛苦Abse4411大大了，

**Comment by abse4411** [comment]
- 针对`或是没有加上@@ 或是 @$`的问题，新版中，只有使用`translate`命令的翻译过文本才会添加‘@@’。‘@$’不会在出现了。
- 针对`一次出現三行出現相同翻譯（新版）`的问题，这个新版本正处于开发阶段，后续将会进行改进。一个可能的解决方案，你可以在[这里（针对google翻译）](https://github.com/abse4411/projz_renpy/blob/47578a9994ef3f815cb65f1b87f0f35d12e3ce12/trans/web_translator.py#L204C1-L212)延长清空延迟时间和进行多次清除 ：
```python
    def clear(self):
        try:
            self.browser.find_element(By.XPATH, '/html/body/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div[1]/div[2]/div[3]/c-wiz[1]/div[1]/div/div[1]/span/button').click()
            self.inputArea.click()
            self.inputArea.send_keys(Keys.CONTROL, 'a')
            self.inputArea.send_keys(Keys.BACKSPACE)
        except:
            self.inputArea.clear()
        time.sleep(random.uniform(0.2, 1))
```
改成：
```python
    def clear(self):
        try:
            self.browser.find_element(By.XPATH, '/html/body/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div[1]/div[2]/div[3]/c-wiz[1]/div[1]/div/div[1]/span/button').click()
        except:
            pass
        time.sleep(0.2) 
        try:
            self.inputArea.click()
            self.inputArea.send_keys(Keys.CONTROL, 'a')
            self.inputArea.send_keys(Keys.BACKSPACE)
        except:
            self.inputArea.clear()
        time.sleep(random.uniform(0.2, 1))

```
这可能会解决你的问题，但是翻译速度可能收到影响。如果他能解决它的问题，期待你的反馈。你的反馈帮助很大，谢谢！

**Comment by BlackZoneJweak** [comment]
谢谢您，我已经测试过了，有关重複翻译问题已经解决没有问题。是否可以把符号＠＄加回，因为这样子比较好检查那一段没有翻译，比较好用find 继续使用中一段时间后再回来告知, 有比较了跟以前的版本几乎是架构分开重写，辛苦您了，谢谢您喔

**Comment by BlackZoneJweak** [comment]
> PS：新的命令已经推出：savehtml和loadhtml，它们以最简单和最快速的方式翻译文本，拉取最新代码以获得最佳体验。
试了6个不同长度的rpy，在两台电脑上做了一样的程序，有时候会翻译出 "{i}xxxxxxx</font><font style="vertical-align: inherit;">去那里可能不是个好主意。{/i}" 出现的机率大约是文本翻译长度的10%，有正常翻译成中文只是连{i}</font><font style..>{/i},因该是如果档案在define 主角有上色的话就会翻译出来(有一些没有上色也会，可是机率比较小)，可是是可以用find 跟 replace all来就修正,谢谢您

**Comment by abse4411** [comment]
> > PS：新的命令已经推出：savehtml和loadhtml，它们以最简单和最快速的方式翻译文本，拉取最新代码以获得最佳体验。
> 
> 试了6个不同长度的rpy，在两台电脑上做了一样的程序，有时候会翻译出 "{i}xxxxxxx去那里可能不是个好主意。{/i}" 出现的机率大约是文本翻译长度的10%，有正常翻译成中文只是连{i}{/i},因该是如果档案在define 主角有上色的话就会翻译出来(有一些没有上色也会，可是机率比较小)，可是是可以用find 跟 replace all来就修正,谢谢您

能提供相关的rpy文件和翻译目标(源语言和目标语言)吗？这里有利于我定位问题。

**Comment by abse4411** [comment]
> > 能提供相关的rpy文件和翻译目标(源语言和目标语言)吗？这里有利于我定位问题。
> 
> 请问大大需要整个游戏，还是只要有问题的rpy??

仅需要有问题的rpy文件即可，以及你想翻译的语言目标。

**Comment by BlackZoneJweak** [comment]
大大這個是一個文件因為目前我不在家裡，手提裡只有這一個檔案，可是當要翻譯繁體中文，西文都碰到同樣的問題，給您當參考
[(https://drive.google.com/drive/folders/1vy2pLQe3Os7CwyWmrA7Q6BifDFMwFZ-4?usp=drive_link)]

**Comment by abse4411** [comment]
> 大大這個是一個文件因為目前我不在家裡，手提裡只有這一個檔案，可是當要翻譯繁體中文，西文都碰到同樣的問題，給您當參考 [(https://drive.google.com/drive/folders/1vy2pLQe3Os7CwyWmrA7Q6BifDFMwFZ-4?usp=drive_link)]

没关系，你可以在任何时候提供文件。这似乎是一个需要权限的链接，请求信息已发出。

**Comment by BlackZoneJweak** [comment]
> 没关系，你可以在任何时候提供文件。这似乎是一个需要权限的链接，请求信息已发出。

權限已給了 xD

**Comment by abse4411** [comment]
> > > PS：新的命令已经推出：savehtml和loadhtml，它们以最简单和最快速的方式翻译文本，拉取最新代码以获得最佳体验。
> > 
> > 
> > 试了6个不同长度的rpy，在两台电脑上做了一样的程序，有时候会翻译出 "{i}xxxxxxx去那里可能不是个好主意。{/i}" 出现的机率大约是文本翻译长度的10%，有正常翻译成中文只是连{i}{/i},因该是如果档案在define 主角有上色的话就会翻译出来(有一些没有上色也会，可是机率比较小)，可是是可以用find 跟 replace all来就修正,谢谢您
> 
> 能提供相关的rpy文件和翻译目标(源语言和目标语言)吗？这里有利于我定位问题。

出现这种情况应该是翻译引擎导致的，因为程序没有直接参与翻译过程。你可以删除 `savehtml`导出的html文件部分行，以减少翻译引擎的内容。注意：翻译引擎无法完全代替人工，因此针对一些翻译文本需要适当的检查。

**Comment by BlackZoneJweak** [comment]
谢谢abse4411大大不断的更新，让翻译语言上越来越简单，小弟我附上小小的自动检查跟取代的py档，给您看看，我目前是用您写出来的软体配我不太成功的python 这样要手动查的部份就真的很少了！！ 谢谢您
[https://drive.google.com/file/d/1gomVMf2YkK88XCS88xOpm8ujjWtIkJ-l/view?usp=drive_link](url)

**Comment by abse4411** [comment]
> 谢谢abse4411大大不断的更新，让翻译语言上越来越简单，小弟我附上小小的自动检查跟取代的py档，给您看看，我目前是用您写出来的软体配我不太成功的python 这样要手动查的部份就真的很少了！！ 谢谢您 https://drive.google.com/file/d/1gomVMf2YkK88XCS88xOpm8ujjWtIkJ-l/view?usp=drive_link

感谢提供代码。针对提供的去除无用html标签(如</font>, </td>)功能，你可以集成到本地代码中，在[这句](https://github.com/abse4411/projz_renpy/blob/9941f1a86a543f34056fcbe52d279bc9c5014700/store/html_store.py#L82)代码前进行预处理。可以尝试新的代码，我在本地电脑使用过程中并未发现有类似`</font><font style="vertical-align: inherit;">`的文本混在翻译中，可以尝试最新版本进行体验。注意现在版本为0.3，与之前版本0.2不兼容，因此任何使用新版本读取proz目录下的pt文件会导致错误，最后的0.2版本见：https://github.com/abse4411/projz_renpy/tree/9a8d98e4f8f1e34ff4e99e27441149fe49b39f25

**Comment by BlackZoneJweak** [comment]
https://drive.google.com/file/d/1wBJJpz16B2_1ScrQMoDG2D57sUv0Da61/view?usp=drive_link
上面是翻译出来的 RPY，这个是游戏名字 Lifeinmiddleeast-v0.1.6，我现在是用 3.0用 sh 翻译后 lh 最后 a 目前大约都是一次翻译5个档案，就有机率出现 font, td ,d5 等等就算是一个档案也会出现有些标签 xD ，我的作业系统是  windows11可是不知道是不是因为多语关西，因为工作上需要所以我的windows是有韩日西葡英繁简中 xD 不知道是不是这个原因，可是我用另一台只有西文的windows也是会出现标籤，我觉得网页翻译比较快xD给您做参考

**Comment by abse4411** [comment]
> https://drive.google.com/file/d/1wBJJpz16B2_1ScrQMoDG2D57sUv0Da61/view?usp=drive_link 上面是翻译出来的 RPY，这个是游戏名字 Lifeinmiddleeast-v0.1.6，我现在是用 3.0用 sh 翻译后 lh 最后 a 目前大约都是一次翻译5个档案，就有机率出现 font, td ,d5 等等就算是一个档案也会出现有些标签 xD ，我的作业系统是 windows11可是不知道是不是因为多语关西，因为工作上需要所以我的windows是有韩日西葡英繁简中 xD 不知道是不是这个原因，可是我用另一台只有西文的windows也是会出现标籤，我觉得网页翻译比较快xD给您做参考

是否使用chrome或者microsoft edge进行网页翻译？或者不是使用官方自带翻译扩展？你可以提供部份使用`savehtml`命令后生成的html文件和翻译过后的html文件，帮助我更好的查找问题。这里面涉及到问题很多，且由于工作原因，进行代码测试可能不会那么及时，请谅解。🙂

**Comment by BlackZoneJweak** [comment]
> 这是似乎chrome游览器才有的问题，请暂时使用microsoft edge进行网页翻译。由于工作原因，代码的更新可能不会那么及时，请谅解。🙂

谢谢大大辛苦了工作第一，测试后用edge 没有出现那个标籤问题，还有一个问题，我的英文不昰很好，所以有很多论坛我都昰用翻译机在浏览,现在有一个问题在翻译游戏时如果昰多语言。譬如说英文那就有英文的字型那如果昰中文想用另外一个字型不然不会出现文字,请问大大知道知道昰在哪一个档案,可以去设定多语言多字形吗？希望大大可以教教我,谢谢。
PS:如果是英文跟西文的话就没有问题,因为是用同一种字型，我目前是修改gui.rpy里的字型只能用一种

**Comment by abse4411** [comment]
> > 这是似乎chrome游览器才有的问题，请暂时使用microsoft edge进行网页翻译。由于工作原因，代码的更新可能不会那么及时，请谅解。🙂
> 
> 谢谢大大辛苦了工作第一，测试后用edge 没有出现那个标籤问题，还有一个问题，我的英文不昰很好，所以有很多论坛我都昰用翻译机在浏览,现在有一个问题在翻译游戏时如果昰多语言。譬如说英文那就有英文的字型那如果昰中文想用另外一个字型不然不会出现文字,请问大大知道知道昰在哪一个档案,可以去设定多语言多字形吗？希望大大可以教教我,谢谢。 PS:如果是英文跟西文的话就没有问题,因为是用同一种字型，我目前是修改gui.rpy里的字型只能用一种

你可以在screen.py 中的perferencc每天添加多语言按钮，添加切换语言的代码并在切换语言后运行设定游戏的字体代码：
```
vbox:
        style_prefix "radio"
        label _("Language")
        textbutton _("English") action Language(None)
        textbutton _("Chinese") text_font "SourceHanSansLite.ttf" action Language("chinese")
```
指定字体的代码：
```
gui.system_font = gui.main_font = gui.text_font = gui.name_text_font = gui.interface_text_font = gui.button_text_font = gui.choice_button_text_font = "XXX.ttf"
```
其中"XXX.ttf"为对应语言的字体。你可能需要重新加载游戏以便字体生效，由于我并不很熟悉renpy开发，这个指引可以参考[这里](https://zhuanlan.zhihu.com/p/463284344#h_463284344_17)

**Comment by BlackZoneJweak** [comment]
> > > 这是似乎chrome游览器才有的问题，请暂时使用microsoft edge进行网页翻译。由于工作原因，代码的更新可能不会那么及时，请谅解。🙂
> > 
> > 
> > 谢谢大大辛苦了工作第一，测试后用edge 没有出现那个标籤问题，还有一个问题，我的英文不昰很好，所以有很多论坛我都昰用翻译机在浏览,现在有一个问题在翻译游戏时如果昰多语言。譬如说英文那就有英文的字型那如果昰中文想用另外一个字型不然不会出现文字,请问大大知道知道昰在哪一个档案,可以去设定多语言多字形吗？希望大大可以教教我,谢谢。 PS:如果是英文跟西文的话就没有问题,因为是用同一种字型，我目前是修改gui.rpy里的字型只能用一种
> 
> 你可以在screen.py 中的perferencc每天添加多语言按钮，添加切换语言的代码并在切换语言后运行设定游戏的字体代码：
> 
> ```
> vbox:
>         style_prefix "radio"
>         label _("Language")
>         textbutton _("English") action Language(None)
>         textbutton _("Chinese") text_font "SourceHanSansLite.ttf" action Language("chinese")
> ```
> 
> 指定字体的代码：
> 
> ```
> gui.system_font = gui.main_font = gui.text_font = gui.name_text_font = gui.interface_text_font = gui.button_text_font = gui.choice_button_text_font = "XXX.ttf"
> ```
> 
> 其中"XXX.ttf"为对应语言的字体。你可能需要重新加载游戏以便字体生效，由于我并不很熟悉renpy开发，这个指引可以参考[这里](https://zhuanlan.zhihu.com/p/463284344#h_463284344_17)

谢谢大大的帮忙跟教导可以了辛苦了

**Comment by BlackZoneJweak** [comment]
呵呵又来回报问题了 3.2版本会有机会很多部份不会翻译到，好像提取翻译部份的机制变多了，很多部份都会被省略（例如有（）会被略过还有一些符号，可是相同用旧版就不会略过）给您参考，我目前还是用sh再做翻译还有大大请问一下AC的作用还是不太懂是说是在LH之后使用让翻译变成100％？ 还是什麽时机使用测试过了，可是还是没有搞懂

**Comment by abse4411** [comment]
> 呵呵又来回报问题了 3.2版本会有机会很多部份不会翻译到，好像提取翻译部份的机制变多了，很多部份都会被省略（例如有（）会被略过还有一些符号，可是相同用旧版就不会略过）给您参考，我目前还是用sh再做翻译还有大大请问一下AC的作用还是不太懂是说是在LH之后使用让翻译变成100％？ 还是什麽时机使用测试过了，可是还是没有搞懂

针对“很多部份都会被省略（例如有（）会被略过还有一些符号，可是相同用旧版就不会略过）给您参考”，可以提供一些原始rpy文件和遗漏的翻译部分截图吗？这有助于我快都定位问题。请发送我的邮箱：shen_zhifeng@outlook.com ，谢谢

针对“AC的作用”： accpt命令用于将一个翻译项目中不需要翻译的文本直接合并到翻译的文本，不需要翻译的文本来自于使用html文件翻译过程中翻译后和原始文本相同的新文本。这些新文本都是些符号的组合，不需要翻译，例如这样文本:
```
# game/ch2script.rpy:472714
translate Chinese_E resetfourtsuneyoanswers_421ae272:

    # t "..........."
    t "..........."
```

假设翻译项目有12条不需要翻译的未翻译的文本，这时候你可以把它们合并翻译的项目中：
unstranslated lines: 12
stranslated lines: 2
使用accpt命令后：
unstranslated lines: 0
stranslated lines: 2+12

您可以添加我的discord账号：xuefeng1064    ，方便实时交流。

**Comment by BlackZoneJweak** [comment]
好的 晚点我在把rpy寄给您，我现在人在外面呵呵，也已经加您的Discord不好意思每次都麻烦您 XD

**Comment by BlackZoneJweak** [comment]
安安哦 大大我回来回报错误了 XD 当我要执行 full.exe
[2023-09-12 13:18:19][parse_console.py:233, tid16224][INFO] - Selecting the default language esp for translating. If you want change to another language, please specify the argument {lang}
[2023-09-12 13:18:21][dl_translator.py:25, tid16224][INFO] - Start loading the mbart50 model
[2023-09-12 13:18:21][dl_translator.py:29, tid16224][INFO] - Loading the mbart50 model from: D:\projzv3\hf_models\mbart50
error: Couldn't instantiate the backend tokenizer from one of:
(1) a `tokenizers` library serialization file,
(2) a slow tokenizer instance to convert or
(3) an equivalent slow tokenizer class to instantiate and convert.
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
[2023-09-12 13:18:21][parse_console.py:420, tid16224][ERROR] - Couldn't instantiate the backend tokenizer from one of:
(1) a `tokenizers` library serialization file,
(2) a slow tokenizer instance to convert or
(3) an equivalent slow tokenizer class to instantiate and convert.
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
Traceback (most recent call last):
  File "parse_console.py", line 417, in main
    register_commands[cmd](*args[1:])
  File "parse_console.py", line 251, in dltranslate_cmd
    t = wt.trans_wrapper(proj, model_name)
  File "trans\ai\dl_translator.py", line 31, in __init__
    self.mt = dlt.TranslationModel(model_path, model_family=model_family)
  File "dl_translate\_translation_model.py", line 112, in __init__
  File "transformers\tokenization_utils_base.py", line 1854, in from_pretrained
  File "transformers\tokenization_utils_base.py", line 2017, in _from_pretrained
  File "transformers\models\mbart50\tokenization_mbart50_fast.py", line 135, in __init__
  File "transformers\tokenization_utils_fast.py", line 119, in __init__
ValueError: Couldn't instantiate the backend tokenizer from one of:
(1) a `tokenizers` library serialization file,
(2) a slow tokenizer instance to convert or
(3) an equivalent slow tokenizer class to instantiate and convert.
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
What is your next step? (Enter a command (case insensitive) or Q/q to exit):
出现这个,所以没有出现选择语言的画面,请问一下是哪里有问题? 有安装requirement.txt
又麻烦您了

**Comment by abse4411** [comment]
> 安安哦 大大我回来回报错误了 XD 当我要执行 full.exe [2023-09-12 13:18:19][parse_console.py:233, tid16224][INFO] - Selecting the default language esp for translating. If you want change to another language, please specify the argument {lang} [2023-09-12 13:18:21][dl_translator.py:25, tid16224][INFO] - Start loading the mbart50 model [2023-09-12 13:18:21][dl_translator.py:29, tid16224][INFO] - Loading the mbart50 model from: D:\projzv3\hf_models\mbart50 error: Couldn't instantiate the backend tokenizer from one of: (1) a `tokenizers` library serialization file, (2) a slow tokenizer instance to convert or (3) an equivalent slow tokenizer class to instantiate and convert. You need to have sentencepiece installed to convert a slow tokenizer to a fast one. [2023-09-12 13:18:21][parse_console.py:420, tid16224][ERROR] - Couldn't instantiate the backend tokenizer from one of: (1) a `tokenizers` library serialization file, (2) a slow tokenizer instance to convert or (3) an equivalent slow tokenizer class to instantiate and convert. You need to have sentencepiece installed to convert a slow tokenizer to a fast one. Traceback (most recent call last): File "parse_console.py", line 417, in main register_commandscmd File "parse_console.py", line 251, in dltranslate_cmd t = wt.trans_wrapper(proj, model_name) File "trans\ai\dl_translator.py", line 31, in **init** self.mt = dlt.TranslationModel(model_path, model_family=model_family) File "dl_translate_translation_model.py", line 112, in **init** File "transformers\tokenization_utils_base.py", line 1854, in from_pretrained File "transformers\tokenization_utils_base.py", line 2017, in _from_pretrained File "transformers\models\mbart50\tokenization_mbart50_fast.py", line 135, in **init** File "transformers\tokenization_utils_fast.py", line 119, in **init** ValueError: Couldn't instantiate the backend tokenizer from one of: (1) a `tokenizers` library serialization file, (2) a slow tokenizer instance to convert or (3) an equivalent slow tokenizer class to instantiate and convert. You need to have sentencepiece installed to convert a slow tokenizer to a fast one. What is your next step? (Enter a command (case insensitive) or Q/q to exit): 出现这个,所以没有出现选择语言的画面,请问一下是哪里有问题? 有安装requirement.txt 又麻烦您了

感谢反馈，修复版本exe已经上传，链接已经更新在readme.md文件中

**Comment by BlackZoneJweak** [comment]
好的 感恩哦 还麻烦您给一下google的权限,因为百度在巴西真的很难连 xD 如果您愿意我下载后,可以上传到 terabox跟mega让更多人可以下载

**Comment by BlackZoneJweak** [comment]
想请问一下大大batch size要如何判断是否设定无错?例如我有3080那因该要设定多大?

**Comment by abse4411** [comment]
> 想请问一下大大batch size要如何判断是否设定无错?例如我有3080那因该要设定多大?

你可以在使用时候根据GPU内存的占用量决定，是使用dlt命令翻译时候，设置一个数值，比如说8，然后通过任务管理器查看GPU的内存占用情况，如果内存没有超出，你可以把数值变大。

由于exe的pytoch版本仅支持CPU，不支持NVIDIA GPU。你需要到通过安装通过本地python3环境安装带有cuda支持的pytorch版本:https://pytorch.org/，GPU的cuda版本可以通过`nvidia-smi`命令查看. 一切就绪后，使用`python3 parse_console.py`运行程序

**Comment by abse4411** [comment]
> 好的 感恩哦 还麻烦您给一下google的权限,因为百度在巴西真的很难连 xD 如果您愿意我下载后,可以上传到 terabox跟mega让更多人可以下载

感谢，已经调整权限：https://drive.google.com/file/d/1oP9XuYUGU4xDGk7OdkPt-31Z-ykffq7q/view?usp=sharing

**Comment by BlackZoneJweak** [comment]
谢谢大大回来回报使用心得如果是用AI翻译的话，准确率很高也可正常使用显卡来加速只是时间比较长，用之前的方式网页翻译的话,速度比较快可是准确率相互比较的话比较低，以上使用心得给您做参考，目前还在详细的使用您开发的软体只要有任何问题、心得都会再跟您回报，谢谢

**Comment by abse4411** [comment]
> 谢谢大大回来回报使用心得如果是用AI翻译的话，准确率很高也可正常使用显卡来加速只是时间比较长，用之前的方式网页翻译的话,速度比较快可是准确率相互比较的话比较低，以上使用心得给您做参考，目前还在详细的使用您开发的软体只要有任何问题、心得都会再跟您回报，谢谢

感谢反馈

**Comment by BlackZoneJweak** [comment]
安安喔 之前工作關西去了鄉下地方網路很差哈哈，我可以幫忙翻譯界面到西文跟葡萄牙文，辛苦您了開發這麼好用的軟體呵呵 對了我有點不懂三個ai翻譯模組有什麼差別，我目前是用m2m100

**Comment by abse4411** [comment]
> 安安喔 之前工作關西去了鄉下地方網路很差哈哈，我可以幫忙翻譯界面到西文跟葡萄牙文，辛苦您了開發這麼好用的軟體呵呵 對了我有點不懂三個ai翻譯模組有什麼差別，我目前是用m2m100

感谢支持，我正在重新整理文档中，您可以继续您的工作，后续如果完成的话，在discord上通知您。
对于这些AI翻译模型，一般来说，模型越大，可以翻译更多语言和具有较高的翻译质量，但这也意味着需要更大GPU内存来加载它们，翻译速度也会下降。您可以选择尝试不同的模型来确定那些模型具有较好的翻译效果。

**Comment by BlackZoneJweak** [comment]
改版后,用AI 会出现 
error: batch_size should be a positive integer value, but got batch_size=0
[2023-10-07 12:00:11][parse_console.py:123, tid10016][ERROR] - batch_size should be a positive integer value, but got batch_size=0
Traceback (most recent call last):
  File "D:\projzv3\parse_console.py", line 120, in main
    execute_cmd(cmd, *args[1:])
  File "D:\projzv3\cmd\__init__.py", line 63, in execute_cmd
    _REGISTERED_CMDS[name](*args)
  File "D:\projzv3\cmd\trans.py", line 63, in dltranslate_cmd
    t.translate_all(lang)
  File "D:\projzv3\trans\ai\dl_translator.py", line 130, in translate_all
    res = self.translate_batch(texts)
  File "D:\projzv3\trans\ai\dl_translator.py", line 148, in translate_batch
    res = self.mt.translate(rawtexts, self.source, self.target, batch_size=len(rawtexts), verbose=False)
  File "C:\Program Files\Python310\lib\site-packages\dl_translate\_translation_model.py", line 177, in translate
    data_loader = torch.utils.data.DataLoader(text, batch_size=batch_size)
  File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 357, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\sampler.py", line 232, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=0
用旧版就不会给您参考

**Comment by abse4411** [comment]
> 改版后, 1.)用AI 会出现 不管那一個模型 error: batch_size should be a positive integer value, but got batch_size=0 [2023-10-07 12:00:11][parse_console.py:123, tid10016][ERROR] - batch_size should be a positive integer value, but got batch_size=0 Traceback (most recent call last): File "D:\projzv3\parse_console.py", line 120, in main execute_cmd(cmd, *args[1:]) File "D:\projzv3\cmd__init__.py", line 63, in execute_cmd _REGISTERED_CMDS[name](*args) File "D:\projzv3\cmd\trans.py", line 63, in dltranslate_cmd t.translate_all(lang) File "D:\projzv3\trans\ai\dl_translator.py", line 130, in translate_all res = self.translate_batch(texts) File "D:\projzv3\trans\ai\dl_translator.py", line 148, in translate_batch res = self.mt.translate(rawtexts, self.source, self.target, batch_size=len(rawtexts), verbose=False) File "C:\Program Files\Python310\lib\site-packages\dl_translate_translation_model.py", line 177, in translate data_loader = torch.utils.data.DataLoader(text, batch_size=batch_size) File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 357, in **init** batch_sampler = BatchSampler(sampler, batch_size, drop_last) File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\sampler.py", line 232, in **init** raise ValueError("batch_size should be a positive integer value, " ValueError: batch_size should be a positive integer value, but got batch_size=0 2.)如果翻译对话有如 old "guy" "xxxxxxxxxxx" new "xxxxxxxxxxx" 只会有对话不会有前一个 "guy" 用旧版就不会给您参考

感谢反馈！
1. 针对第一个问题，这是由于空文本导致batch=0，已经在最新提交修复。
2. 针对第二个问题，是否可以提供完整rpy文件用于参考，可直接在discord发送给我。目前正在研究多种情况，谢谢。

**Comment by abse4411** [comment]
> 改版后, 1.)用AI 会出现 不管那一個模型 error: batch_size should be a positive integer value, but got batch_size=0 [2023-10-07 12:00:11][parse_console.py:123, tid10016][ERROR] - batch_size should be a positive integer value, but got batch_size=0 Traceback (most recent call last): File "D:\projzv3\parse_console.py", line 120, in main execute_cmd(cmd, *args[1:]) File "D:\projzv3\cmd__init__.py", line 63, in execute_cmd _REGISTERED_CMDS[name](*args) File "D:\projzv3\cmd\trans.py", line 63, in dltranslate_cmd t.translate_all(lang) File "D:\projzv3\trans\ai\dl_translator.py", line 130, in translate_all res = self.translate_batch(texts) File "D:\projzv3\trans\ai\dl_translator.py", line 148, in translate_batch res = self.mt.translate(rawtexts, self.source, self.target, batch_size=len(rawtexts), verbose=False) File "C:\Program Files\Python310\lib\site-packages\dl_translate_translation_model.py", line 177, in translate data_loader = torch.utils.data.DataLoader(text, batch_size=batch_size) File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 357, in **init** batch_sampler = BatchSampler(sampler, batch_size, drop_last) File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\sampler.py", line 232, in **init** raise ValueError("batch_size should be a positive integer value, " ValueError: batch_size should be a positive integer value, but got batch_size=0 2.)如果翻译对话有如 old "guy" "xxxxxxxxxxx" new "xxxxxxxxxxx" 只会有对话不会有前一个 "guy" 用旧版就不会给您参考

问题应该在最新的提交的得到解决了

**Comment by BlackZoneJweak** [comment]
- m2m100 文本翻译辞意 85%，可是 \[] {} 遗失大约 15%，如果有 mmmmmm 模音译词会变成,,,,, 或是一些符号3%，速度较快
- nllb200 文本翻译辞意 90%，可是 \[] {} 遗失大约 18%，如果有 mmmmmm 模音译词会变成,,,,, 或是一些符号6%，速度适中
- mbart50 文本翻译辞意 95%，可是 \[] {} 遗失大约 20%，如果有 mmmmmm 模音译词会变成,,,,, 或是一些符号6%，速度超慢
- WEB全页翻译文本翻译辞意 85%，可是 \[] {} 遗失大约 5%，如果有 mmmmmm 模音译词会变成,,,,, 或是一些符号1%，速度最快
  给您作参考以上都是用同一台電腦測試 Asus ZEP. Laptop rtx3080 40GB 测试过英文转外文 中文都是差不多的结果

**Comment by abse4411** [comment]
> * m2m100 文本翻译辞意 85%，可是 [] {} 遗失大约 15%，如果有 mmmmmm 模音译词会变成,,,,, 或是一些符号3%，速度较快
> * nllb200 文本翻译辞意 90%，可是 [] {} 遗失大约 18%，如果有 mmmmmm 模音译词会变成,,,,, 或是一些符号6%，速度适中
> * mbart50 文本翻译辞意 95%，可是 [] {} 遗失大约 20%，如果有 mmmmmm 模音译词会变成,,,,, 或是一些符号6%，速度超慢
> * WEB全页翻译文本翻译辞意 85%，可是 [] {} 遗失大约 5%，如果有 mmmmmm 模音译词会变成,,,,, 或是一些符号1%，速度最快
>   给您作参考以上都是用同一台電腦測試 Asus ZEP. Laptop rtx3080 40GB 测试过英文转外文 中文都是差不多的结果

感谢反馈。由于机器翻译始终无法与人类翻译相媲美。针对[]或者{}的丢失，可以使用dump命令导出excel文件后手动检查并修改，然后使用update命令更新即可。

**Comment by BlackZoneJweak** [comment]
> 感谢反馈。由于机器翻译始终无法与人类翻译相媲美。针对[]或者{}的丢失，可以使用dump命令导出excel文件后手动检查并修改，然后使用update命令更新即可。
是谢谢您,我目前大致上都是用web或是ai nllb200 之后,在用以个python指令来寻找 [] {} 等等 xD
