### ISSUE TITLE
蹲大佬

### ISSUE THREAD

**Issue by julienslink** [abse4411/projz_renpy_translation#4]
坐等作者大大更新导出excel功能，
由于我用的是AiNiee来用gpt翻译文本，但是它只支持excel或者json文件导入和导出，我试着把它导出的excel另存为html，但是这样的html没能成功识别，提示utf8编码不支持啥的
蹲个大佬教教我怎么excel文件转成支持的html，多谢多谢

**Comment by abse4411** [comment]
感谢支持，excel正在开发中

**Comment by abse4411** [comment]
你好，excel导入导出功能已经实现，你可以把翻译的文本按顺序粘贴到`saveexcel`命令导出的excel文件中，然后使用`loadexcel`命令实现翻译

**Comment by julienslink** [comment]
> 你好，excel导入导出功能已经实现，你可以把翻译的文本按顺序粘贴到`saveexcel`命令导出的excel文件中，然后使用`loadexcel`命令实现翻译

感谢大佬ORZ

**Comment by julienslink** [comment]
今天才发现，这个跳过errorhandling部分的功能太贴心了，免去机翻后手动修改，给大佬赞一个
