### ISSUE TITLE
翻译文本为空时不会自动跳过

### ISSUE THREAD

**Issue by epq1176** [abse4411/projz_renpy_translation#5]
生成的翻译文本中存在空文本时，脚本可能会多次使用上一句的翻译，并再放回时省略掉目标文本的引号

**Comment by abse4411** [comment]
感谢反馈。在最新的提交中修复了如果当前翻译文本和上一次一样的问题。对于引号的问题，可能是翻译引擎的问题，代码不会对引号进行处理。你可以来提供详细的rpy文件和翻译参数设置来帮我进一步确认问题，谢谢。

**Comment by epq1176** [comment]
就是这样：
```
# game/scripts/day26.rpy:619
translate chinese christiesexend_9f420b02:

    # Dad "Whatever you say boss."
    Dad "@$随你怎么说，老大。"

# game/scripts/day26.rpy:622
translate chinese christiesexend_0ae9bcd0_1:

    # ""
@@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？"@@所以你早就知道，但还是参与了？"@@所以你早就知道，但还是参与了？
@@所以你早就知道，但还是参与了？
```

**Comment by abse4411** [comment]
> 就是这样：
> 
> ```
> # game/scripts/day26.rpy:619
> translate chinese christiesexend_9f420b02:
> 
>     # Dad "Whatever you say boss."
>     Dad "@$随你怎么说，老大。"
> 
> # game/scripts/day26.rpy:622
> translate chinese christiesexend_0ae9bcd0_1:
> 
>     # ""
> @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？"@@所以你早就知道，但还是参与了？"@@所以你早就知道，但还是参与了？
> @@所以你早就知道，但还是参与了？
> ```

感谢，空文本会导致网页翻译让程序等待超时， 最新提交（fac32b76643383b5350d2c1fc3483d1a95fc77d9）跳过对空文本的翻译

**Comment by abse4411** [comment]
> 就是这样：
> 
> ```
> # game/scripts/day26.rpy:619
> translate chinese christiesexend_9f420b02:
> 
>     # Dad "Whatever you say boss."
>     Dad "@$随你怎么说，老大。"
> 
> # game/scripts/day26.rpy:622
> translate chinese christiesexend_0ae9bcd0_1:
> 
>     # ""
> @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？ @@所以你早就知道，但还是参与了？"@@所以你早就知道，但还是参与了？"@@所以你早就知道，但还是参与了？
> @@所以你早就知道，但还是参与了？
> ```

当原始文本为空的时候使用apply命令替换文本会丢失引号，最新提交中修复这个问题
