### ISSUE TITLE
当角色名内有引号时翻译有误

### ISSUE THREAD

**Issue by epq1176** [abse4411/projz_renpy_translation#8]
```
# game/chapter1/ch1afterback.rpy:81
translate chinese ch1afterback_9b893d82:

    # "*Unknown Hooden Woman*" "Hello agent [pl]."
    "@@“你好 [pl]探员”。"

# game/chapter1/ch1afterback.rpy:83
translate chinese ch1afterback_97e0fbf8:

    # "*Unknown Hooded Woman*" "He's here."
    "@@“他来了。"

# game/chapter1/ch1afterback.rpy:84
translate chinese ch1afterback_b28faf94:

    # "*Unknown Hooded Woman*" "..."
    "@@* 未知兜帽女 * “ ...”。"
```

**Comment by abse4411** [comment]
> ```
> # game/chapter1/ch1afterback.rpy:81
> translate chinese ch1afterback_9b893d82:
> 
>     # "*Unknown Hooden Woman*" "Hello agent [pl]."
>     "@@“你好 [pl]探员”。"
> 
> # game/chapter1/ch1afterback.rpy:83
> translate chinese ch1afterback_97e0fbf8:
> 
>     # "*Unknown Hooded Woman*" "He's here."
>     "@@“他来了。"
> 
> # game/chapter1/ch1afterback.rpy:84
> translate chinese ch1afterback_b28faf94:
> 
>     # "*Unknown Hooded Woman*" "..."
>     "@@* 未知兜帽女 * “ ...”。"
> ```

如果使用web翻译的话，发现Caiyun会无法翻译*Unknown Hooded Woman*，请使用baidu或者其他翻译api

**Comment by epq1176** [comment]
"*Unknown Hooded Woman*"因为是对话所属的角色id，不需要翻译，但因为加上了引号，脚本似乎将角色id和对应的文本一同当作需要翻译的文本进行翻译，导致游戏中对话相对应的角色文本缺失

**Comment by abse4411** [comment]
> "_Unknown Hooded Woman_"因为是对话所属的角色id，不需要翻译，但因为加上了引号，脚本似乎将角色id和对应的文本一同当作需要翻译的文本进行翻译，导致游戏中对话相对应的角色文本缺失

了解   后面将考虑这种情况

**Comment by abse4411** [comment]
> 还有，能否将浏览器线程的设置从ini换到控制台？



> "_Unknown Hooded Woman_"因为是对话所属的角色id，不需要翻译，但因为加上了引号，脚本似乎将角色id和对应的文本一同当作需要翻译的文本进行翻译，导致游戏中对话相对应的角色文本缺失



新版本已经修复上述问题
