### ISSUE TITLE
能否使用谷歌的文档翻译功能进行快速批量翻译

### ISSUE THREAD

**Issue by Orga-Itsuka** [abse4411/projz_renpy_translation#9]
文本量较大的游戏使用API或者HTML的翻译速度都比较慢。
尤其是HTML的网页翻译会分段加载，可能需要使用鼠标滚轮翻动几千页来保证edge的页面翻译能够完全工作。
google提供了.docx文档翻译功能，是否可以添加功能，导出.docx文档，使用不会被翻译的纯数字串作为索引进行批量翻译？

**Comment by abse4411** [comment]
你好，你可以通过`saveexcel`命令将未翻译文本导出的为excel文件后在上传至Google翻译，这也是支持的。一旦翻译完成后，你需要把excel表第一行内容修改为原始的内容：
```txt
Translation Index (Don't modify)	Raw Text	Translated Text
```
之后覆盖原始导出的为excel文件，用`loadexcel`命令导入即可。由于excel表第一行内容是`loadexcel`命令识别依据，因此需要保证第一行内容不被改变。建议在操作之前将代码拉取到最新版本再操作。

**Comment by abse4411** [comment]
如果坚持要用doc文档翻译，请把saveexcel命令导出excel内容粘贴到doc内（保持表格形式不变），翻译完成后重新复制到原始导出的excel文件，再用loadexcel命令导入即可。
![image](https://github.com/abse4411/projz_renpy_translation/assets/29497928/4b9d8e80-8635-4421-9b7c-aa822a46a0b9)

**Comment by BlackZoneJweak** [comment]
> 文本量较大的游戏使用API或者HTML的翻译速度都比较慢。 尤其是HTML的网页翻译会分段加载，可能需要使用鼠标滚轮翻动几千页来保证edge的页面翻译能够完全工作。 google提供了.docx文档翻译功能，是否可以添加功能，导出.docx文档，使用不会被翻译的纯数字串作为索引进行批量翻译？

我是用python控制自动run page down 延迟 1.5秒 给您做参考
